/**
 * @file kyc-seeds.data.ts
 * @description Comprehensive seed data for Syrian KYC system
 * 
 * FEATURES:
 * - 8-state KYC workflow test data
 * - Syrian document types (National ID, Business License, Tax Certificate, etc.)
 * - Complete regulatory compliance scenarios
 * - Arabic/English localization
 * - Enterprise-grade validation data
 * - Performance testing scenarios
 * 
 * @author SouqSyria Development Team
 * @since 2025-08-20
 */

import {
  SyrianKycStatus,
  SyrianKycVerificationLevel,
  SyrianKycDocumentType,
  SyrianKycPriority,
  SyrianKycRejectionReason,
  SyrianGovernorateCode,
} from '../enums/syrian-kyc.enums';

/**
 * Sample KYC documents for different workflow states
 */
export const SAMPLE_KYC_DOCUMENTS_SEED = [
  {
    // APPROVED Syrian National ID
    documentType: SyrianKycDocumentType.SYRIAN_ID,
    titleEn: 'Syrian National ID Card',
    titleAr: 'البطاقة الشخصية السورية',
    status: SyrianKycStatus.APPROVED,
    verificationLevel: SyrianKycVerificationLevel.BASIC,
    fileDetails: {
      originalUrl: 'https://storage.souqsyria.com/kyc/syrian_id_001.jpg',
      thumbnailUrl: 'https://storage.souqsyria.com/kyc/thumb_001.jpg',
      fileName: 'syrian_id_001.jpg',
      fileSize: 2048576,
      mimeType: 'image/jpeg',
      uploadedAt: new Date('2025-08-18T10:00:00.000Z'),
      checksum: 'sha256:abc123def456...',
    },
    documentData: {
      documentNumber: '12345678901',
      fullName: 'أحمد محمد الأحمد',
      fullNameEn: 'Ahmad Mohammed Al-Ahmad',
      dateOfBirth: '1990-01-15',
      placeOfBirth: 'Damascus',
      placeOfBirthAr: 'دمشق',
      nationality: 'Syrian',
      nationalityAr: 'سوري',
      gender: 'Male',
      genderAr: 'ذكر',
      issueDate: '2020-01-01',
      expiryDate: '2030-01-01',
      issuingAuthority: 'Ministry of Interior',
      issuingAuthorityAr: 'وزارة الداخلية',
    },
    addressInfo: {
      addressLine1: 'Damascus, Mazzeh District',
      addressLine1Ar: 'دمشق، حي المزة',
      addressLine2: 'Building 15, Floor 3',
      addressLine2Ar: 'البناء رقم 15، الطابق الثالث',
      postalCode: '12345',
      phone: '+963987654321',
      email: 'ahmad@example.com',
    },
    validationResults: {
      isValid: true,
      validationScore: 96.5,
      complianceLevel: 'HIGH' as const,
      ocrConfidence: 98.2,
      faceMatchScore: 94.1,
      documentAuthenticity: true,
      riskScore: 8.3,
      validationChecks: {
        formatValid: true,
        checksumValid: true,
        expDateValid: true,
        issuerValid: true,
        duplicateCheck: false,
      },
      validationErrors: [],
      validationWarnings: [],
    },
    reviewNotes: 'Document approved. Clear image quality, all information valid.',
    reviewNotesAr: 'تمت الموافقة على الوثيقة. جودة صورة واضحة، جميع المعلومات صحيحة.',
    reviewedAt: new Date('2025-08-18T14:30:00.000Z'),
    expiresAt: new Date('2030-01-01T00:00:00.000Z'),
    renewalRequiredAt: new Date('2029-01-01T00:00:00.000Z'),
    renewalNotificationSent: false,
    complianceData: {
      complianceChecks: {
        sanctionsCheck: 'CLEAR' as const,
        pepsCheck: 'CLEAR' as const,
        amlCheck: 'LOW_RISK' as const,
        kycTier: 'TIER_2' as const,
      },
      riskAssessment: {
        overallRisk: 'LOW' as const,
        riskScore: 12.5,
        riskFactors: ['NEW_CUSTOMER'],
        mitigatingFactors: ['VALID_DOCUMENTS', 'GOOD_REFERENCES', 'LOCAL_ADDRESS'],
      },
      regulatoryFlags: [],
      lastComplianceCheck: new Date('2025-08-18T14:00:00.000Z'),
    },
    slaTracking: {
      slaHours: 72,
      expectedReviewTime: new Date('2025-08-21T10:00:00.000Z'),
      isOverdue: false,
      hoursOverdue: 0,
      escalationLevel: 0,
      processingTime: 28.5,
      onTimeProcessing: true,
      delayReasons: [],
    },
    priority: 'NORMAL' as const,
    isActive: true,
    clientIp: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X)',
  },
  {
    // UNDER_REVIEW Business License
    documentType: SyrianKycDocumentType.BUSINESS_LICENSE,
    titleEn: 'Commercial Business License',
    titleAr: 'رخصة العمل التجاري',
    status: SyrianKycStatus.UNDER_REVIEW,
    verificationLevel: SyrianKycVerificationLevel.BUSINESS,
    fileDetails: {
      originalUrl: 'https://storage.souqsyria.com/kyc/business_license_002.jpg',
      thumbnailUrl: 'https://storage.souqsyria.com/kyc/thumb_002.jpg',
      fileName: 'business_license_002.jpg',
      fileSize: 3145728,
      mimeType: 'image/jpeg',
      uploadedAt: new Date('2025-08-19T09:00:00.000Z'),
      checksum: 'sha256:def456ghi789...',
    },
    documentData: {
      documentNumber: 'BL-2025-001234',
      businessName: 'Damascus Tech Solutions',
      businessNameAr: 'دمشق لحلول التقنية',
      businessType: 'Information Technology Services',
      businessTypeAr: 'خدمات تقنية المعلومات',
      registrationNumber: 'REG-2025-5678',
      taxId: 'TAX-987654321',
      chamberNumber: 'CC-2025-1111',
      fullName: 'مريم أحمد السوري',
      fullNameEn: 'Mariam Ahmad Al-Souri',
      issueDate: '2025-01-15',
      expiryDate: '2026-01-15',
      issuingAuthority: 'Ministry of Economy and Foreign Trade',
      issuingAuthorityAr: 'وزارة الاقتصاد والتجارة الخارجية',
    },
    addressInfo: {
      addressLine1: 'Damascus, Malki District',
      addressLine1Ar: 'دمشق، حي المالكي',
      addressLine2: 'Technology Center, Office 201',
      addressLine2Ar: 'مركز التقنية، مكتب رقم 201',
      postalCode: '11511',
      phone: '+963113456789',
      email: 'info@damascustech.sy',
    },
    validationResults: {
      isValid: true,
      validationScore: 88.7,
      complianceLevel: 'MEDIUM' as const,
      ocrConfidence: 92.5,
      documentAuthenticity: true,
      riskScore: 15.2,
      validationChecks: {
        formatValid: true,
        checksumValid: true,
        expDateValid: true,
        issuerValid: true,
        duplicateCheck: false,
      },
      validationErrors: [],
      validationWarnings: ['Business address requires verification'],
    },
    complianceData: {
      complianceChecks: {
        sanctionsCheck: 'CLEAR' as const,
        pepsCheck: 'PENDING' as const,
        amlCheck: 'LOW_RISK' as const,
        kycTier: 'TIER_3' as const,
      },
      riskAssessment: {
        overallRisk: 'MEDIUM' as const,
        riskScore: 25.8,
        riskFactors: ['NEW_BUSINESS', 'TECH_SECTOR'],
        mitigatingFactors: ['REGISTERED_BUSINESS', 'LOCAL_CHAMBER_MEMBER'],
      },
      regulatoryFlags: ['PENDING_CHAMBER_VERIFICATION'],
      lastComplianceCheck: new Date('2025-08-19T09:30:00.000Z'),
    },
    slaTracking: {
      slaHours: 120,
      expectedReviewTime: new Date('2025-08-24T09:00:00.000Z'),
      isOverdue: false,
      hoursOverdue: 0,
      escalationLevel: 0,
      processingTime: null,
      onTimeProcessing: null,
      delayReasons: [],
    },
    priority: 'HIGH' as const,
    isActive: true,
    clientIp: '192.168.1.105',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
  },
  {
    // REQUIRES_CLARIFICATION Tax Certificate
    documentType: SyrianKycDocumentType.TAX_CERTIFICATE,
    titleEn: 'Tax Registration Certificate',
    titleAr: 'شهادة تسجيل ضريبي',
    status: SyrianKycStatus.REQUIRES_CLARIFICATION,
    verificationLevel: SyrianKycVerificationLevel.BUSINESS,
    fileDetails: {
      originalUrl: 'https://storage.souqsyria.com/kyc/tax_cert_003.jpg',
      thumbnailUrl: 'https://storage.souqsyria.com/kyc/thumb_003.jpg',
      fileName: 'tax_cert_003.jpg',
      fileSize: 1572864,
      mimeType: 'image/jpeg',
      uploadedAt: new Date('2025-08-17T15:30:00.000Z'),
      checksum: 'sha256:ghi789jkl012...',
    },
    documentData: {
      documentNumber: 'TAX-2024-567890',
      businessName: 'Aleppo Import Export Co.',
      businessNameAr: 'شركة حلب للاستيراد والتصدير',
      taxId: 'TAX-123456789',
      registrationNumber: 'TR-2024-9876',
      fullName: 'خالد عبد الرحمن الحلبي',
      fullNameEn: 'Khaled Abdul Rahman Al-Halabi',
      issueDate: '2024-03-10',
      expiryDate: '2025-03-10',
      issuingAuthority: 'General Authority for Taxes and Fees',
      issuingAuthorityAr: 'الهيئة العامة للضرائب والرسوم',
    },
    validationResults: {
      isValid: false,
      validationScore: 65.3,
      complianceLevel: 'LOW' as const,
      ocrConfidence: 78.9,
      documentAuthenticity: true,
      riskScore: 35.7,
      validationChecks: {
        formatValid: true,
        checksumValid: false,
        expDateValid: false,
        issuerValid: true,
        duplicateCheck: false,
      },
      validationErrors: ['Document appears to be expired', 'Checksum validation failed'],
      validationWarnings: ['Low OCR confidence on some fields'],
    },
    reviewNotes: 'Document requires clarification. Please provide updated tax certificate.',
    reviewNotesAr: 'الوثيقة تحتاج توضيح. يرجى تقديم شهادة ضريبية محدثة.',
    reviewedAt: new Date('2025-08-18T11:15:00.000Z'),
    expiresAt: new Date('2025-03-10T00:00:00.000Z'),
    renewalRequiredAt: new Date('2025-02-10T00:00:00.000Z'),
    renewalNotificationSent: true,
    complianceData: {
      complianceChecks: {
        sanctionsCheck: 'CLEAR' as const,
        pepsCheck: 'CLEAR' as const,
        amlCheck: 'MEDIUM_RISK' as const,
        kycTier: 'TIER_2' as const,
      },
      riskAssessment: {
        overallRisk: 'MEDIUM' as const,
        riskScore: 42.1,
        riskFactors: ['EXPIRED_DOCUMENT', 'IMPORT_EXPORT_BUSINESS', 'CROSS_BORDER_ACTIVITY'],
        mitigatingFactors: ['ESTABLISHED_BUSINESS', 'CLEAN_SANCTIONS_RECORD'],
      },
      regulatoryFlags: ['EXPIRED_TAX_CERTIFICATE', 'REQUIRES_RENEWAL'],
      lastComplianceCheck: new Date('2025-08-18T11:00:00.000Z'),
    },
    slaTracking: {
      slaHours: 72,
      expectedReviewTime: new Date('2025-08-20T15:30:00.000Z'),
      isOverdue: true,
      hoursOverdue: 12.5,
      escalationLevel: 1,
      processingTime: 44.25,
      onTimeProcessing: false,
      delayReasons: ['CLARIFICATION_REQUESTED', 'AWAITING_CUSTOMER_RESPONSE'],
    },
    priority: 'URGENT' as const,
    isActive: true,
    clientIp: '192.168.1.110',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
  },
  {
    // REJECTED Bank Statement
    documentType: SyrianKycDocumentType.BANK_STATEMENT,
    titleEn: 'Bank Account Statement',
    titleAr: 'كشف حساب مصرفي',
    status: SyrianKycStatus.REJECTED,
    verificationLevel: SyrianKycVerificationLevel.BUSINESS,
    fileDetails: {
      originalUrl: 'https://storage.souqsyria.com/kyc/bank_stmt_004.pdf',
      thumbnailUrl: 'https://storage.souqsyria.com/kyc/thumb_004.jpg',
      fileName: 'bank_stmt_004.pdf',
      fileSize: 512000,
      mimeType: 'application/pdf',
      uploadedAt: new Date('2025-08-16T14:20:00.000Z'),
      checksum: 'sha256:jkl012mno345...',
    },
    documentData: {
      documentNumber: 'STMT-2025-08-001',
      fullName: 'سارة محمد الدمشقي',
      fullNameEn: 'Sara Mohammed Al-Dimashqi',
      issueDate: '2025-08-01',
      issuingAuthority: 'Central Bank of Syria',
      issuingAuthorityAr: 'مصرف سورية المركزي',
    },
    validationResults: {
      isValid: false,
      validationScore: 32.1,
      complianceLevel: 'LOW' as const,
      ocrConfidence: 45.6,
      documentAuthenticity: false,
      riskScore: 78.9,
      validationChecks: {
        formatValid: false,
        checksumValid: false,
        expDateValid: true,
        issuerValid: false,
        duplicateCheck: true,
      },
      validationErrors: [
        'Document format does not match bank standards',
        'Potential document tampering detected',
        'Duplicate document submission',
      ],
      validationWarnings: ['Very low OCR confidence', 'Suspicious formatting patterns'],
    },
    reviewNotes: 'Document rejected due to authenticity concerns and format violations.',
    reviewNotesAr: 'تم رفض الوثيقة بسبب مخاوف الأصالة ومخالفات التنسيق.',
    reviewedAt: new Date('2025-08-17T09:45:00.000Z'),
    complianceData: {
      complianceChecks: {
        sanctionsCheck: 'CLEAR' as const,
        pepsCheck: 'CLEAR' as const,
        amlCheck: 'HIGH_RISK' as const,
        kycTier: 'TIER_1' as const,
      },
      riskAssessment: {
        overallRisk: 'HIGH' as const,
        riskScore: 85.2,
        riskFactors: ['DOCUMENT_TAMPERING', 'DUPLICATE_SUBMISSION', 'SUSPICIOUS_PATTERNS'],
        mitigatingFactors: ['CLEAN_SANCTIONS_RECORD'],
      },
      regulatoryFlags: ['SUSPECTED_FRAUD', 'DOCUMENT_TAMPERING', 'REQUIRES_INVESTIGATION'],
      lastComplianceCheck: new Date('2025-08-17T09:30:00.000Z'),
    },
    slaTracking: {
      slaHours: 48,
      expectedReviewTime: new Date('2025-08-18T14:20:00.000Z'),
      isOverdue: false,
      hoursOverdue: 0,
      escalationLevel: 2,
      processingTime: 19.4,
      onTimeProcessing: true,
      delayReasons: ['SECURITY_REVIEW', 'FRAUD_INVESTIGATION'],
    },
    priority: 'CRITICAL' as const,
    isActive: true,
    clientIp: '192.168.1.115',
    userAgent: 'Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36',
  },
  {
    // SUBMITTED Chamber of Commerce Certificate
    documentType: SyrianKycDocumentType.CHAMBER_OF_COMMERCE,
    titleEn: 'Chamber of Commerce Certificate',
    titleAr: 'شهادة غرفة التجارة',
    status: SyrianKycStatus.SUBMITTED,
    verificationLevel: SyrianKycVerificationLevel.CORPORATE,
    fileDetails: {
      originalUrl: 'https://storage.souqsyria.com/kyc/chamber_cert_005.jpg',
      thumbnailUrl: 'https://storage.souqsyria.com/kyc/thumb_005.jpg',
      fileName: 'chamber_cert_005.jpg',
      fileSize: 2621440,
      mimeType: 'image/jpeg',
      uploadedAt: new Date('2025-08-20T08:00:00.000Z'),
      checksum: 'sha256:mno345pqr678...',
    },
    documentData: {
      documentNumber: 'CC-2025-112233',
      businessName: 'Syrian Steel Industries Ltd.',
      businessNameAr: 'الصناعات الفولاذية السورية المحدودة',
      businessType: 'Manufacturing - Steel Processing',
      businessTypeAr: 'التصنيع - معالجة الفولاذ',
      registrationNumber: 'SSI-2025-001',
      chamberNumber: 'CHAMBER-ALB-2025-1122',
      fullName: 'يوسف علي الصناعي',
      fullNameEn: 'Youssef Ali Al-Sinaai',
      issueDate: '2025-07-01',
      expiryDate: '2026-07-01',
      issuingAuthority: 'Aleppo Chamber of Commerce',
      issuingAuthorityAr: 'غرفة تجارة حلب',
    },
    addressInfo: {
      addressLine1: 'Aleppo Industrial Zone',
      addressLine1Ar: 'المنطقة الصناعية حلب',
      addressLine2: 'Block C, Factory 15',
      addressLine2Ar: 'البلوك ج، المصنع رقم 15',
      postalCode: '21500',
      phone: '+963212345678',
      email: 'contact@syriansteel.sy',
    },
    validationResults: {
      isValid: true,
      validationScore: 91.8,
      complianceLevel: 'HIGH' as const,
      ocrConfidence: 95.7,
      documentAuthenticity: true,
      riskScore: 18.5,
      validationChecks: {
        formatValid: true,
        checksumValid: true,
        expDateValid: true,
        issuerValid: true,
        duplicateCheck: false,
      },
      validationErrors: [],
      validationWarnings: ['Large corporation - requires enhanced due diligence'],
    },
    complianceData: {
      complianceChecks: {
        sanctionsCheck: 'PENDING' as const,
        pepsCheck: 'PENDING' as const,
        amlCheck: 'MEDIUM_RISK' as const,
        kycTier: 'TIER_4' as const,
      },
      riskAssessment: {
        overallRisk: 'MEDIUM' as const,
        riskScore: 35.6,
        riskFactors: ['LARGE_CORPORATION', 'MANUFACTURING_SECTOR', 'HIGH_VALUE_TRANSACTIONS'],
        mitigatingFactors: ['CHAMBER_MEMBER', 'ESTABLISHED_BUSINESS', 'TRANSPARENT_OWNERSHIP'],
      },
      regulatoryFlags: ['ENHANCED_DUE_DILIGENCE_REQUIRED', 'LARGE_CORP_REVIEW'],
      lastComplianceCheck: new Date('2025-08-20T08:30:00.000Z'),
    },
    slaTracking: {
      slaHours: 168, // 7 days for corporate verification
      expectedReviewTime: new Date('2025-08-27T08:00:00.000Z'),
      isOverdue: false,
      hoursOverdue: 0,
      escalationLevel: 0,
      processingTime: null,
      onTimeProcessing: null,
      delayReasons: [],
    },
    priority: 'HIGH' as const,
    isActive: true,
    clientIp: '192.168.1.120',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101',
  }
];

/**
 * Sample KYC status logs for workflow testing
 */
export const SAMPLE_KYC_STATUS_LOGS_SEED = [
  {
    previousStatus: null,
    newStatus: SyrianKycStatus.DRAFT,
    notes: 'Document created in draft status',
    notesAr: 'تم إنشاء الوثيقة في حالة المسودة',
    metadata: {
      source: 'web_app',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X)',
      ipAddress: '192.168.1.100',
    },
  },
  {
    previousStatus: SyrianKycStatus.DRAFT,
    newStatus: SyrianKycStatus.SUBMITTED,
    notes: 'Document submitted for review',
    notesAr: 'تم تقديم الوثيقة للمراجعة',
    metadata: {
      source: 'mobile_app',
      submitAction: 'user_submit',
      validationPassed: true,
    },
  },
  {
    previousStatus: SyrianKycStatus.SUBMITTED,
    newStatus: SyrianKycStatus.UNDER_REVIEW,
    notes: 'Document assigned to reviewer Ahmad Al-Murajiee',
    notesAr: 'تم تعيين الوثيقة للمراجع أحمد المراجع',
    metadata: {
      reviewerName: 'Ahmad Al-Murajiee',
      assignedAt: new Date().toISOString(),
      expectedCompletion: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    previousStatus: SyrianKycStatus.UNDER_REVIEW,
    newStatus: SyrianKycStatus.APPROVED,
    notes: 'Document approved after thorough verification',
    notesAr: 'تمت الموافقة على الوثيقة بعد التحقق الشامل',
    metadata: {
      reviewerNotes: 'All validation checks passed. Document authentic and complete.',
      reviewerNotesAr: 'تم اجتياز جميع فحوصات التحقق. الوثيقة أصلية وكاملة.',
      reviewDuration: '28.5 hours',
      validationScore: 96.5,
    },
  },
];

/**
 * Performance testing data for bulk KYC operations
 */
export const BULK_KYC_GENERATION_CONFIG = {
  documentTypes: [
    SyrianKycDocumentType.SYRIAN_ID,
    SyrianKycDocumentType.BUSINESS_LICENSE,
    SyrianKycDocumentType.TAX_CERTIFICATE,
    SyrianKycDocumentType.CHAMBER_OF_COMMERCE,
    SyrianKycDocumentType.BANK_STATEMENT,
  ],
  statuses: [
    SyrianKycStatus.DRAFT,
    SyrianKycStatus.SUBMITTED,
    SyrianKycStatus.UNDER_REVIEW,
    SyrianKycStatus.APPROVED,
    SyrianKycStatus.REQUIRES_CLARIFICATION,
    SyrianKycStatus.REJECTED,
  ],
  verificationLevels: [
    SyrianKycVerificationLevel.BASIC,
    SyrianKycVerificationLevel.BUSINESS,
    SyrianKycVerificationLevel.CORPORATE,
    SyrianKycVerificationLevel.PREMIUM,
  ],
  priorities: [
    'LOW' as const,
    'NORMAL' as const,
    'HIGH' as const,
    'URGENT' as const,
  ],
  governorateCodes: [
    SyrianGovernorateCode.DAMASCUS,
    SyrianGovernorateCode.ALEPPO,
    SyrianGovernorateCode.HOMS,
    SyrianGovernorateCode.LATTAKIA,
    SyrianGovernorateCode.HAMA,
  ],
};