/**
 * @file hero-banners-seeds.data.ts
 * @description Comprehensive Syrian-themed hero banner test data for SouqSyria platform
 *
 * This file contains 20+ meticulously crafted hero banners showcasing:
 * - Damascus crafts and artisans (Damascus steel, traditional textiles, woodwork)
 * - Aleppo soap campaigns and traditional products
 * - Syrian heritage products from UNESCO-recognized crafts
 * - Ramadan/Eid seasonal campaigns with cultural sensitivity
 * - Regional specialties from all 14 Syrian governorates
 * - Diaspora-targeted content for international Syrian community
 *
 * Banner Types:
 * - product_spotlight: Feature specific traditional products
 * - seasonal: Cultural events (Ramadan, Eid, Independence Day)
 * - flash_sale: Limited-time promotional campaigns
 * - brand_story: Syrian artisan storytelling
 * - cultural: Heritage and UNESCO-recognized crafts
 *
 * @author SouqSyria Development Team
 * @since 2025-11-10
 */

/**
 * Syrian Hero Banner Seed Data
 *
 * Each banner includes:
 * - Complete bilingual content (Arabic/English)
 * - Responsive images (desktop, tablet, mobile)
 * - Scheduling and analytics fields
 * - Syrian cultural context (artisans, regions, UNESCO status)
 * - Target audience (local/diaspora/both)
 */
export const heroBannersSeedData = [
  // ============================================
  // DAMASCUS CRAFTS & ARTISANS (Banners 1-5)
  // ============================================

  {
    // Banner 1: Damascus Steel Heritage Collection
    nameEn: 'Damascus Steel Heritage Campaign',
    nameAr: 'حملة تراث الفولاذ الدمشقي',
    headlineEn: 'Authentic Damascus Steel Collection',
    headlineAr: 'مجموعة الفولاذ الدمشقي الأصيل',
    subheadlineEn: 'Handcrafted by Syrian artisans using 1000-year-old techniques',
    subheadlineAr: 'صُنع يدوياً من قبل الحرفيين السوريين بتقنيات عمرها ألف عام',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/damascus-steel-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/damascus-steel-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/damascus-steel-mobile-768x400.jpg',
    imageAltEn: 'Damascus Steel Heritage Collection',
    imageAltAr: 'مجموعة تراث الفولاذ الدمشقي',
    ctaTextEn: 'Explore Collection',
    ctaTextAr: 'استكشف المجموعة',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'arrow_forward',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/damascus-steel',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'damascus-steel-heritage-2025',
    textColor: 'light',
    overlayColor: '#000000',
    overlayOpacity: 0.4,
    contentAlignment: 'left',
    contentVerticalAlignment: 'center',
    type: 'cultural',
    priority: 10,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Damascus',
    syrianSpecialties: ['Damascus Steel', 'Traditional Forging', 'Pattern Welding'],
    culturalContextEn: 'Damascus steel is renowned worldwide for its distinctive patterns and exceptional strength. This UNESCO-recognized craft has been perfected over millennia in the heart of Damascus Old City.',
    culturalContextAr: 'يشتهر الفولاذ الدمشقي في جميع أنحاء العالم بأنماطه المميزة وقوته الاستثنائية. تم إتقان هذه الحرفة المعترف بها من قبل اليونسكو على مدى آلاف السنين في قلب مدينة دمشق القديمة.',
    unescoRecognition: true,
    artisanNameEn: 'Master Ahmad Al-Dimashqi',
    artisanNameAr: 'الأستاذ أحمد الدمشقي',
    artisanBioEn: 'Master Ahmad has been crafting Damascus steel for 35 years, following his family\'s 4-generation tradition. His workshop in Damascus Old City is a living museum of this ancient craft.',
    artisanBioAr: 'يصنع الأستاذ أحمد الفولاذ الدمشقي منذ 35 عاماً، متبعاً تقليد عائلته الممتد لأربعة أجيال. ورشته في دمشق القديمة هي متحف حي لهذه الحرفة القديمة.',
    artisanLocation: 'Damascus Old City',
    artisanExperience: 35,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 2: Damascus Brocade Fashion
    nameEn: 'Damascus Brocade Spring Collection',
    nameAr: 'مجموعة البروكار الدمشقي الربيعية',
    headlineEn: 'Luxury Damascus Brocade Fabrics',
    headlineAr: 'أقمشة البروكار الدمشقي الفاخرة',
    subheadlineEn: 'Handwoven silk and gold thread masterpieces',
    subheadlineAr: 'تحف منسوجة يدوياً من الحرير وخيوط الذهب',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/brocade-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/brocade-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/brocade-mobile-768x400.jpg',
    imageAltEn: 'Damascus Brocade Spring Collection',
    imageAltAr: 'مجموعة البروكار الدمشقي الربيعية',
    ctaTextEn: 'Shop Brocade',
    ctaTextAr: 'تسوق البروكار',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'shopping_bag',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/damascus-brocade',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'brocade-spring-2025',
    textColor: 'light',
    overlayColor: '#1a237e',
    overlayOpacity: 0.3,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 9,
    scheduleStart: new Date('2025-03-01T00:00:00Z'),
    scheduleEnd: new Date('2025-06-30T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Damascus',
    syrianSpecialties: ['Damascus Brocade', 'Silk Weaving', 'Gold Thread Embroidery'],
    culturalContextEn: 'Damascus brocade (البروكار الدمشقي) has adorned royalty and nobility for centuries. This luxurious silk fabric with intricate gold and silver patterns represents the pinnacle of Syrian textile artistry.',
    culturalContextAr: 'زيّن البروكار الدمشقي الملوك والنبلاء لقرون. يمثل هذا القماش الحريري الفاخر بأنماطه المعقدة من الذهب والفضة قمة الفن النسيجي السوري.',
    unescoRecognition: true,
    artisanNameEn: 'Master Sami Al-Shami',
    artisanNameAr: 'الأستاذ سامي الشامي',
    artisanBioEn: 'Master Sami is a third-generation brocade weaver, preserving the intricate patterns and techniques that have made Damascus brocade world-famous.',
    artisanBioAr: 'الأستاذ سامي هو نساج بروكار من الجيل الثالث، يحافظ على الأنماط والتقنيات المعقدة التي جعلت البروكار الدمشقي مشهوراً عالمياً.',
    artisanLocation: 'Damascus Souq Al-Hamidiyeh',
    artisanExperience: 28,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 3: Damascus Woodwork & Inlay
    nameEn: 'Damascus Mosaic Woodwork Campaign',
    nameAr: 'حملة الخشب المطعم الدمشقي',
    headlineEn: 'Exquisite Damascus Mosaic Furniture',
    headlineAr: 'أثاث الموزاييك الدمشقي الرائع',
    subheadlineEn: 'Mother-of-pearl inlay masterpieces for your home',
    subheadlineAr: 'تحف مطعمة بالصدف لمنزلك',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/mosaic-woodwork-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/mosaic-woodwork-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/mosaic-woodwork-mobile-768x400.jpg',
    imageAltEn: 'Damascus Mosaic Woodwork',
    imageAltAr: 'الخشب المطعم الدمشقي',
    ctaTextEn: 'Discover Craftsmanship',
    ctaTextAr: 'اكتشف الحرفية',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'arrow_forward',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/damascus-woodwork',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'damascus-woodwork-2025',
    textColor: 'light',
    overlayColor: '#2e7d32',
    overlayOpacity: 0.35,
    contentAlignment: 'right',
    contentVerticalAlignment: 'center',
    type: 'cultural',
    priority: 8,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Damascus',
    syrianSpecialties: ['Mosaic Woodwork', 'Mother-of-Pearl Inlay', 'Geometric Patterns'],
    culturalContextEn: 'Damascus mosaic woodwork (الخشب المطعم) is a meticulous craft where thousands of tiny pieces of wood, mother-of-pearl, and ivory create breathtaking geometric patterns.',
    culturalContextAr: 'الخشب المطعم الدمشقي هو حرفة دقيقة حيث تُنشئ آلاف القطع الصغيرة من الخشب والصدف والعاج أنماطاً هندسية خلابة.',
    unescoRecognition: true,
    artisanNameEn: 'Master Ibrahim Al-Najjar',
    artisanNameAr: 'الأستاذ إبراهيم النجار',
    artisanBioEn: 'Master Ibrahim has dedicated 40 years to perfecting the art of mosaic woodwork, creating pieces that are displayed in museums worldwide.',
    artisanBioAr: 'كرس الأستاذ إبراهيم 40 عاماً لإتقان فن الخشب المطعم، وصنع قطعاً معروضة في متاحف حول العالم.',
    artisanLocation: 'Damascus Old City',
    artisanExperience: 40,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 4: Damascus Old City Treasures
    nameEn: 'Damascus Old City Heritage Campaign',
    nameAr: 'حملة تراث دمشق القديمة',
    headlineEn: 'Treasures from Damascus Old City',
    headlineAr: 'كنوز من دمشق القديمة',
    subheadlineEn: 'Discover UNESCO World Heritage craftsmanship',
    subheadlineAr: 'اكتشف حرفية التراث العالمي لليونسكو',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/old-damascus-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/old-damascus-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/old-damascus-mobile-768x400.jpg',
    imageAltEn: 'Damascus Old City Treasures',
    imageAltAr: 'كنوز دمشق القديمة',
    ctaTextEn: 'Explore Heritage',
    ctaTextAr: 'استكشف التراث',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'explore',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/damascus-heritage',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'damascus-heritage-2025',
    textColor: 'light',
    overlayColor: '#5d4037',
    overlayOpacity: 0.4,
    contentAlignment: 'left',
    contentVerticalAlignment: 'center',
    type: 'cultural',
    priority: 9,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Damascus',
    syrianSpecialties: ['Traditional Crafts', 'Heritage Products', 'Artisan Goods'],
    culturalContextEn: 'Damascus Old City is a UNESCO World Heritage site and home to generations of master artisans. Each product tells a story of Syrian cultural heritage.',
    culturalContextAr: 'دمشق القديمة هي موقع تراث عالمي لليونسكو وموطن لأجيال من الحرفيين الأساتذة. كل منتج يحكي قصة من التراث الثقافي السوري.',
    unescoRecognition: true,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Damascus Old City',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 5: Damascus Rose Products
    nameEn: 'Damascus Rose Beauty Collection',
    nameAr: 'مجموعة جمال الورد الدمشقي',
    headlineEn: 'Pure Damascus Rose Essence',
    headlineAr: 'جوهر الورد الدمشقي النقي',
    subheadlineEn: 'Natural beauty products from Syria\'s legendary roses',
    subheadlineAr: 'منتجات جمال طبيعية من ورود سوريا الأسطورية',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/damascus-rose-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/damascus-rose-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/damascus-rose-mobile-768x400.jpg',
    imageAltEn: 'Damascus Rose Beauty Collection',
    imageAltAr: 'مجموعة جمال الورد الدمشقي',
    ctaTextEn: 'Shop Rose Products',
    ctaTextAr: 'تسوق منتجات الورد',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'syrian-red',
    ctaIcon: 'local_florist',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/damascus-rose',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'damascus-rose-2025',
    textColor: 'dark',
    overlayColor: '#fce4ec',
    overlayOpacity: 0.6,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 7,
    scheduleStart: new Date('2025-04-01T00:00:00Z'),
    scheduleEnd: new Date('2025-06-30T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Damascus',
    syrianSpecialties: ['Rose Water', 'Rose Oil', 'Natural Cosmetics'],
    culturalContextEn: 'The Damascus rose (Rosa damascena) has been cultivated in Syria for over 3,000 years. Its essential oil is one of the most precious and expensive in the world.',
    culturalContextAr: 'تمت زراعة الورد الدمشقي في سوريا لأكثر من 3000 عام. زيته الأساسي هو واحد من أثمن وأغلى الزيوت في العالم.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Al-Mrah Region, Damascus',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  // ============================================
  // ALEPPO SOAP & TRADITIONAL PRODUCTS (Banners 6-8)
  // ============================================

  {
    // Banner 6: Aleppo Soap Heritage
    nameEn: 'Authentic Aleppo Soap Campaign',
    nameAr: 'حملة صابون حلب الأصيل',
    headlineEn: '100% Pure Aleppo Soap',
    headlineAr: 'صابون حلب النقي 100%',
    subheadlineEn: 'Handmade with olive oil and laurel for 1,000+ years',
    subheadlineAr: 'مصنوع يدوياً بزيت الزيتون والغار لأكثر من 1000 عام',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/aleppo-soap-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/aleppo-soap-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/aleppo-soap-mobile-768x400.jpg',
    imageAltEn: 'Authentic Aleppo Soap',
    imageAltAr: 'صابون حلب الأصيل',
    ctaTextEn: 'Buy Aleppo Soap',
    ctaTextAr: 'اشتري صابون حلب',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'shopping_cart',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'product',
    targetUrl: '/product/aleppo-soap-original',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'aleppo-soap-2025',
    textColor: 'light',
    overlayColor: '#2e7d32',
    overlayOpacity: 0.4,
    contentAlignment: 'left',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 9,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Aleppo',
    syrianSpecialties: ['Aleppo Soap', 'Olive Oil', 'Laurel Berry Oil'],
    culturalContextEn: 'Aleppo soap (صابون حلب) is the world\'s oldest soap, dating back to the 8th century. Made from 100% natural olive and laurel oils, it\'s renowned for its skin benefits.',
    culturalContextAr: 'صابون حلب هو أقدم صابون في العالم، يعود تاريخه إلى القرن الثامن. مصنوع من زيت الزيتون والغار الطبيعي 100%، ومشهور بفوائده للبشرة.',
    unescoRecognition: true,
    artisanNameEn: 'Master Nabil Al-Halabi',
    artisanNameAr: 'الأستاذ نبيل الحلبي',
    artisanBioEn: 'Master Nabil represents the 5th generation of his family\'s soap-making dynasty in Aleppo. His traditional methods preserve the authentic recipe unchanged for centuries.',
    artisanBioAr: 'الأستاذ نبيل يمثل الجيل الخامس من سلالة عائلته في صناعة الصابون في حلب. طرقه التقليدية تحافظ على الوصفة الأصيلة دون تغيير لقرون.',
    artisanLocation: 'Aleppo Old City',
    artisanExperience: 32,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 7: Aleppo Speed (Local Shipping Campaign)
    nameEn: 'Aleppo Speed Delivery Launch',
    nameAr: 'إطلاق توصيل حلب السريع',
    headlineEn: 'Fast Delivery from Aleppo',
    headlineAr: 'توصيل سريع من حلب',
    subheadlineEn: 'Your orders delivered within 48 hours across Syria',
    subheadlineAr: 'طلباتك تصل خلال 48 ساعة في جميع أنحاء سوريا',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/aleppo-delivery-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/aleppo-delivery-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/aleppo-delivery-mobile-768x400.jpg',
    imageAltEn: 'Aleppo Speed Delivery Service',
    imageAltAr: 'خدمة توصيل حلب السريع',
    ctaTextEn: 'Learn More',
    ctaTextAr: 'اعرف المزيد',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'syrian-red',
    ctaIcon: 'local_shipping',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'page',
    targetUrl: '/shipping-info',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'aleppo-speed-launch-2025',
    textColor: 'light',
    overlayColor: '#c62828',
    overlayOpacity: 0.5,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'brand_story',
    priority: 8,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-03-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Aleppo',
    syrianSpecialties: null,
    culturalContextEn: 'Aleppo Speed is our local shipping partner committed to fast, reliable delivery across all 14 Syrian governorates.',
    culturalContextAr: 'حلب السريع هو شريكنا المحلي في الشحن الملتزم بالتوصيل السريع والموثوق في جميع المحافظات السورية الـ14.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 8: Aleppo Pistachios
    nameEn: 'Premium Aleppo Pistachios Campaign',
    nameAr: 'حملة الفستق الحلبي الفاخر',
    headlineEn: 'World-Famous Aleppo Pistachios',
    headlineAr: 'الفستق الحلبي الشهير عالمياً',
    subheadlineEn: 'Sweet, flavorful, and sustainably harvested',
    subheadlineAr: 'حلو، لذيذ، ومحصود بشكل مستدام',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/aleppo-pistachios-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/aleppo-pistachios-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/aleppo-pistachios-mobile-768x400.jpg',
    imageAltEn: 'Premium Aleppo Pistachios',
    imageAltAr: 'الفستق الحلبي الفاخر',
    ctaTextEn: 'Shop Pistachios',
    ctaTextAr: 'تسوق الفستق',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'add_shopping_cart',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'product',
    targetUrl: '/product/aleppo-pistachios-premium',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'aleppo-pistachios-2025',
    textColor: 'light',
    overlayColor: '#558b2f',
    overlayOpacity: 0.35,
    contentAlignment: 'right',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 7,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Aleppo',
    syrianSpecialties: ['Aleppo Pistachios', 'Gourmet Nuts', 'Natural Snacks'],
    culturalContextEn: 'Aleppo pistachios are considered among the finest in the world, known for their distinctive sweet flavor and bright green color. Perfect for snacking or traditional Syrian desserts.',
    culturalContextAr: 'يُعتبر الفستق الحلبي من أفضل أنواع الفستق في العالم، ومعروف بنكهته الحلوة المميزة ولونه الأخضر الزاهي. مثالي للتسلية أو الحلويات السورية التقليدية.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Aleppo Countryside',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  // ============================================
  // RAMADAN & EID SEASONAL CAMPAIGNS (Banners 9-12)
  // ============================================

  {
    // Banner 9: Ramadan Kareem 2025
    nameEn: 'Ramadan Kareem 2025 Campaign',
    nameAr: 'حملة رمضان كريم 2025',
    headlineEn: 'Ramadan Kareem',
    headlineAr: 'رمضان كريم',
    subheadlineEn: 'Special offers on dates, nuts, sweets, and prayer items',
    subheadlineAr: 'عروض خاصة على التمور والمكسرات والحلويات ومستلزمات الصلاة',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/ramadan-2025-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/ramadan-2025-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/ramadan-2025-mobile-768x400.jpg',
    imageAltEn: 'Ramadan Kareem 2025',
    imageAltAr: 'رمضان كريم 2025',
    ctaTextEn: 'Shop Ramadan Essentials',
    ctaTextAr: 'تسوق مستلزمات رمضان',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'star',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'campaign',
    targetUrl: '/campaigns/ramadan-2025',
    trackingSource: 'hero-slider',
    trackingMedium: 'seasonal',
    trackingCampaign: 'ramadan-2025',
    textColor: 'light',
    overlayColor: '#283593',
    overlayOpacity: 0.5,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'seasonal',
    priority: 10,
    scheduleStart: new Date('2025-02-28T00:00:00Z'), // Start of Ramadan 2025 (approx)
    scheduleEnd: new Date('2025-03-30T23:59:59Z'), // End of Ramadan 2025 (approx)
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: ['Dates', 'Nuts', 'Sweets', 'Prayer Items'],
    culturalContextEn: 'Ramadan is the holiest month in Islam. We\'ve curated special offers on dates, traditional sweets, prayer items, and gifts to make your Ramadan blessed and convenient.',
    culturalContextAr: 'رمضان هو الشهر الأقدس في الإسلام. قمنا بتنسيق عروض خاصة على التمور والحلويات التقليدية ومستلزمات الصلاة والهدايا لجعل رمضانك مباركاً ومريحاً.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: false, // Activate when Ramadan approaches
  },

  {
    // Banner 10: Eid Al-Fitr 2025
    nameEn: 'Eid Al-Fitr 2025 Campaign',
    nameAr: 'حملة عيد الفطر 2025',
    headlineEn: 'Eid Mubarak',
    headlineAr: 'عيد مبارك',
    subheadlineEn: 'Celebrate with new clothes, gifts, and sweets',
    subheadlineAr: 'احتفل بالملابس الجديدة والهدايا والحلويات',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/eid-fitr-2025-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/eid-fitr-2025-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/eid-fitr-2025-mobile-768x400.jpg',
    imageAltEn: 'Eid Al-Fitr 2025',
    imageAltAr: 'عيد الفطر 2025',
    ctaTextEn: 'Shop Eid Gifts',
    ctaTextAr: 'تسوق هدايا العيد',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'syrian-red',
    ctaIcon: 'card_giftcard',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'campaign',
    targetUrl: '/campaigns/eid-fitr-2025',
    trackingSource: 'hero-slider',
    trackingMedium: 'seasonal',
    trackingCampaign: 'eid-fitr-2025',
    textColor: 'light',
    overlayColor: '#c62828',
    overlayOpacity: 0.4,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'seasonal',
    priority: 10,
    scheduleStart: new Date('2025-03-28T00:00:00Z'), // 3 days before Eid
    scheduleEnd: new Date('2025-04-01T23:59:59Z'), // Eid + 2 days
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: ['Traditional Clothing', 'Gifts', 'Sweets', 'Toys'],
    culturalContextEn: 'Eid Al-Fitr marks the end of Ramadan. Celebrate with your loved ones with our curated collection of traditional clothing, gifts, sweets, and toys for children.',
    culturalContextAr: 'عيد الفطر يمثل نهاية رمضان. احتفل مع أحبائك بمجموعتنا المنسقة من الملابس التقليدية والهدايا والحلويات وألعاب الأطفال.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: false, // Activate when Eid approaches
  },

  {
    // Banner 11: Eid Al-Adha 2025
    nameEn: 'Eid Al-Adha 2025 Campaign',
    nameAr: 'حملة عيد الأضحى 2025',
    headlineEn: 'Eid Al-Adha Mubarak',
    headlineAr: 'عيد الأضحى مبارك',
    subheadlineEn: 'Traditional gifts and essentials for the blessed occasion',
    subheadlineAr: 'هدايا تقليدية ومستلزمات للمناسبة المباركة',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/eid-adha-2025-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/eid-adha-2025-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/eid-adha-2025-mobile-768x400.jpg',
    imageAltEn: 'Eid Al-Adha 2025',
    imageAltAr: 'عيد الأضحى 2025',
    ctaTextEn: 'Shop Now',
    ctaTextAr: 'تسوق الآن',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'shopping_bag',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'campaign',
    targetUrl: '/campaigns/eid-adha-2025',
    trackingSource: 'hero-slider',
    trackingMedium: 'seasonal',
    trackingCampaign: 'eid-adha-2025',
    textColor: 'light',
    overlayColor: '#1b5e20',
    overlayOpacity: 0.5,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'seasonal',
    priority: 10,
    scheduleStart: new Date('2025-06-04T00:00:00Z'), // Start of Eid Al-Adha 2025 (approx)
    scheduleEnd: new Date('2025-06-08T23:59:59Z'), // End of Eid Al-Adha celebration (approx)
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: ['Traditional Gifts', 'Clothing', 'Kitchen Essentials'],
    culturalContextEn: 'Eid Al-Adha (Feast of Sacrifice) is one of Islam\'s most important holidays. Shop for traditional gifts, clothing, and essentials for your family celebrations.',
    culturalContextAr: 'عيد الأضحى (عيد القربان) هو واحد من أهم أعياد الإسلام. تسوق للهدايا التقليدية والملابس والمستلزمات لاحتفالات عائلتك.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: false, // Activate when Eid approaches
  },

  {
    // Banner 12: Syrian Independence Day 2025
    nameEn: 'Syrian Independence Day 2025 Campaign',
    nameAr: 'حملة عيد الاستقلال السوري 2025',
    headlineEn: 'Celebrating Syrian Independence',
    headlineAr: 'نحتفل بعيد الاستقلال السوري',
    subheadlineEn: 'April 17 - Honoring our heritage and culture',
    subheadlineAr: '17 نيسان - نكرم تراثنا وثقافتنا',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/independence-day-2025-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/independence-day-2025-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/independence-day-2025-mobile-768x400.jpg',
    imageAltEn: 'Syrian Independence Day 2025',
    imageAltAr: 'عيد الاستقلال السوري 2025',
    ctaTextEn: 'Explore Syrian Heritage',
    ctaTextAr: 'استكشف التراث السوري',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'syrian-red',
    ctaIcon: 'flag',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'campaign',
    targetUrl: '/campaigns/independence-day-2025',
    trackingSource: 'hero-slider',
    trackingMedium: 'seasonal',
    trackingCampaign: 'independence-day-2025',
    textColor: 'light',
    overlayColor: '#CE1126', // Syrian flag red
    overlayOpacity: 0.5,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'seasonal',
    priority: 10,
    scheduleStart: new Date('2025-04-15T00:00:00Z'),
    scheduleEnd: new Date('2025-04-18T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: ['Syrian Handicrafts', 'Traditional Products', 'Heritage Items'],
    culturalContextEn: 'April 17 marks Syria\'s independence from French mandate in 1946. Celebrate Syrian heritage with our curated collection of traditional handicrafts and cultural products.',
    culturalContextAr: '17 نيسان يمثل استقلال سوريا عن الانتداب الفرنسي في 1946. احتفل بالتراث السوري بمجموعتنا المنسقة من الحرف اليدوية التقليدية والمنتجات الثقافية.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: false, // Activate around Independence Day
  },

  // ============================================
  // REGIONAL SPECIALTIES (Banners 13-17)
  // ============================================

  {
    // Banner 13: Palmyra Dates & Desert Products
    nameEn: 'Palmyra Desert Treasures Campaign',
    nameAr: 'حملة كنوز صحراء تدمر',
    headlineEn: 'Premium Palmyra Dates',
    headlineAr: 'تمور تدمر الفاخرة',
    subheadlineEn: 'Sweet dates from the ancient city of Palmyra',
    subheadlineAr: 'تمور حلوة من مدينة تدمر الأثرية',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/palmyra-dates-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/palmyra-dates-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/palmyra-dates-mobile-768x400.jpg',
    imageAltEn: 'Premium Palmyra Dates',
    imageAltAr: 'تمور تدمر الفاخرة',
    ctaTextEn: 'Shop Dates',
    ctaTextAr: 'تسوق التمور',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'shopping_cart',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/palmyra-dates',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'palmyra-dates-2025',
    textColor: 'light',
    overlayColor: '#bf360c',
    overlayOpacity: 0.4,
    contentAlignment: 'left',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 6,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Homs (Palmyra)',
    syrianSpecialties: ['Dates', 'Desert Honey', 'Traditional Sweets'],
    culturalContextEn: 'Palmyra, a UNESCO World Heritage site, is famous for its sweet dates grown in desert oases. These dates have been a staple food for millennia.',
    culturalContextAr: 'تدمر، موقع تراث عالمي لليونسكو، مشهورة بتمورها الحلوة المزروعة في واحات الصحراء. هذه التمور كانت غذاءً أساسياً لآلاف السنين.',
    unescoRecognition: true,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Palmyra Oases',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 14: Latakia Citrus & Coastal Products
    nameEn: 'Latakia Coastal Treasures Campaign',
    nameAr: 'حملة كنوز ساحل اللاذقية',
    headlineEn: 'Fresh from the Mediterranean Coast',
    headlineAr: 'طازج من الساحل المتوسطي',
    subheadlineEn: 'Premium citrus, olive oil, and coastal delicacies',
    subheadlineAr: 'حمضيات فاخرة، زيت زيتون، ولذائذ ساحلية',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/latakia-coastal-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/latakia-coastal-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/latakia-coastal-mobile-768x400.jpg',
    imageAltEn: 'Latakia Coastal Treasures',
    imageAltAr: 'كنوز ساحل اللاذقية',
    ctaTextEn: 'Discover Coastal Products',
    ctaTextAr: 'اكتشف المنتجات الساحلية',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'explore',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/latakia-products',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'latakia-coastal-2025',
    textColor: 'light',
    overlayColor: '#006064',
    overlayOpacity: 0.45,
    contentAlignment: 'right',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 6,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Latakia',
    syrianSpecialties: ['Citrus Fruits', 'Olive Oil', 'Seafood', 'Coastal Crafts'],
    culturalContextEn: 'Latakia, on Syria\'s Mediterranean coast, is renowned for its citrus groves, premium olive oil, and unique coastal crafts influenced by centuries of maritime trade.',
    culturalContextAr: 'اللاذقية، على الساحل السوري المتوسطي، مشهورة ببساتين الحمضيات وزيت الزيتون الفاخر والحرف الساحلية الفريدة المتأثرة بقرون من التجارة البحرية.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Latakia Coast',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 15: Hama Water Wheels Heritage
    nameEn: 'Hama Heritage Campaign',
    nameAr: 'حملة تراث حماة',
    headlineEn: 'Treasures from the City of Water Wheels',
    headlineAr: 'كنوز من مدينة النواعير',
    subheadlineEn: 'Traditional crafts from historic Hama',
    subheadlineAr: 'حرف تقليدية من حماة التاريخية',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/hama-heritage-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/hama-heritage-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/hama-heritage-mobile-768x400.jpg',
    imageAltEn: 'Hama Heritage Products',
    imageAltAr: 'منتجات تراث حماة',
    ctaTextEn: 'Explore Hama Crafts',
    ctaTextAr: 'استكشف حرف حماة',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'arrow_forward',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/hama-crafts',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'hama-heritage-2025',
    textColor: 'light',
    overlayColor: '#1976d2',
    overlayOpacity: 0.4,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'cultural',
    priority: 5,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Hama',
    syrianSpecialties: ['Traditional Pottery', 'Textiles', 'Agricultural Products'],
    culturalContextEn: 'Hama is famous for its massive wooden water wheels (norias) and rich agricultural heritage. The city\'s traditional crafts reflect its connection to the Orontes River.',
    culturalContextAr: 'حماة مشهورة بنواعيرها الخشبية الضخمة وتراثها الزراعي الغني. تعكس حرف المدينة التقليدية ارتباطها بنهر العاصي.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Hama',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 16: Tartus Coastal Products
    nameEn: 'Tartus Mediterranean Delights Campaign',
    nameAr: 'حملة لذائذ طرطوس المتوسطية',
    headlineEn: 'Mediterranean Flavors from Tartus',
    headlineAr: 'نكهات متوسطية من طرطوس',
    subheadlineEn: 'Olive oil, seafood, and coastal crafts',
    subheadlineAr: 'زيت زيتون، مأكولات بحرية، وحرف ساحلية',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/tartus-mediterranean-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/tartus-mediterranean-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/tartus-mediterranean-mobile-768x400.jpg',
    imageAltEn: 'Tartus Mediterranean Products',
    imageAltAr: 'منتجات طرطوس المتوسطية',
    ctaTextEn: 'Shop Coastal Products',
    ctaTextAr: 'تسوق المنتجات الساحلية',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'waves',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/tartus-products',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'tartus-mediterranean-2025',
    textColor: 'light',
    overlayColor: '#0277bd',
    overlayOpacity: 0.4,
    contentAlignment: 'left',
    contentVerticalAlignment: 'center',
    type: 'product_spotlight',
    priority: 5,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Tartus',
    syrianSpecialties: ['Olive Oil', 'Seafood', 'Coastal Crafts', 'Citrus'],
    culturalContextEn: 'Tartus, Syria\'s second major port city, offers premium olive oil, fresh seafood, and traditional coastal crafts influenced by Mediterranean maritime culture.',
    culturalContextAr: 'طرطوس، ثاني أكبر مدينة ميناء في سوريا، تقدم زيت زيتون فاخر، مأكولات بحرية طازجة، وحرف ساحلية تقليدية متأثرة بالثقافة البحرية المتوسطية.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Tartus Coast',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 17: Sweida Druze Heritage
    nameEn: 'Sweida Heritage Campaign',
    nameAr: 'حملة تراث السويداء',
    headlineEn: 'Treasures from Jabal Al-Druze',
    headlineAr: 'كنوز من جبل الدروز',
    subheadlineEn: 'Traditional Druze crafts and mountain products',
    subheadlineAr: 'حرف درزية تقليدية ومنتجات جبلية',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/sweida-heritage-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/sweida-heritage-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/sweida-heritage-mobile-768x400.jpg',
    imageAltEn: 'Sweida Heritage Products',
    imageAltAr: 'منتجات تراث السويداء',
    ctaTextEn: 'Explore Heritage',
    ctaTextAr: 'استكشف التراث',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'terrain',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/sweida-heritage',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'sweida-heritage-2025',
    textColor: 'light',
    overlayColor: '#4e342e',
    overlayOpacity: 0.45,
    contentAlignment: 'right',
    contentVerticalAlignment: 'center',
    type: 'cultural',
    priority: 5,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Sweida',
    syrianSpecialties: ['Druze Crafts', 'Mountain Honey', 'Traditional Clothing', 'Basalt Stone Crafts'],
    culturalContextEn: 'Sweida (Jabal Al-Druze) is home to unique Druze cultural traditions, mountain honey, and distinctive black basalt stone crafts that reflect the region\'s volcanic heritage.',
    culturalContextAr: 'السويداء (جبل الدروز) هي موطن لتقاليد ثقافية درزية فريدة، وعسل جبلي، وحرف حجر البازلت الأسود المميزة التي تعكس التراث البركاني للمنطقة.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Jabal Al-Druze',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  // ============================================
  // DIASPORA-TARGETED CAMPAIGNS (Banners 18-20)
  // ============================================

  {
    // Banner 18: International Shipping Campaign
    nameEn: 'Worldwide Shipping Campaign',
    nameAr: 'حملة الشحن العالمي',
    headlineEn: 'Syrian Heritage, Delivered Worldwide',
    headlineAr: 'التراث السوري، يُسلّم في جميع أنحاء العالم',
    subheadlineEn: 'We ship authentic Syrian products to 50+ countries',
    subheadlineAr: 'نشحن المنتجات السورية الأصيلة إلى أكثر من 50 دولة',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/worldwide-shipping-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/worldwide-shipping-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/worldwide-shipping-mobile-768x400.jpg',
    imageAltEn: 'Worldwide Shipping Service',
    imageAltAr: 'خدمة الشحن العالمي',
    ctaTextEn: 'See Shipping Info',
    ctaTextAr: 'معلومات الشحن',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'syrian-red',
    ctaIcon: 'public',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'page',
    targetUrl: '/international-shipping',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'worldwide-shipping-2025',
    textColor: 'light',
    overlayColor: '#1565c0',
    overlayOpacity: 0.5,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'brand_story',
    priority: 7,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: null,
    culturalContextEn: 'For our Syrian diaspora community worldwide, we offer reliable international shipping to bring a taste of home to your doorstep, wherever you are.',
    culturalContextAr: 'لمجتمع الجالية السورية في جميع أنحاء العالم، نقدم شحناً دولياً موثوقاً لإحضار طعم الوطن إلى عتبة بابك، أينما كنت.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 19: Diaspora Welcome Banner
    nameEn: 'Welcome Home - Diaspora Campaign',
    nameAr: 'أهلاً بك في الوطن - حملة المغتربين',
    headlineEn: 'A Taste of Home, Delivered to You',
    headlineAr: 'طعم الوطن، يُسلّم إليك',
    subheadlineEn: 'Authentic Syrian products for Syrians abroad',
    subheadlineAr: 'منتجات سورية أصيلة للسوريين في المهجر',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/diaspora-welcome-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/diaspora-welcome-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/diaspora-welcome-mobile-768x400.jpg',
    imageAltEn: 'Welcome Home - Diaspora',
    imageAltAr: 'أهلاً بك في الوطن - المغتربين',
    ctaTextEn: 'Shop for Diaspora',
    ctaTextAr: 'تسوق للمغتربين',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'favorite',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'category',
    targetUrl: '/category/diaspora-collection',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'diaspora-welcome-2025',
    textColor: 'light',
    overlayColor: '#c62828',
    overlayOpacity: 0.4,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'brand_story',
    priority: 8,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: ['Damascus Steel', 'Aleppo Soap', 'Traditional Foods', 'Handicrafts'],
    culturalContextEn: 'We understand the longing for home. Our curated diaspora collection brings authentic Syrian products to Syrians living abroad in Europe, Americas, and Australia.',
    culturalContextAr: 'نفهم الشوق للوطن. مجموعتنا المنسقة للمغتربين تحضر المنتجات السورية الأصيلة للسوريين المقيمين في أوروبا وأمريكا وأستراليا.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  {
    // Banner 20: Multi-Currency Support
    nameEn: 'Multi-Currency Support Campaign',
    nameAr: 'حملة دعم العملات المتعددة',
    headlineEn: 'Shop in Your Currency',
    headlineAr: 'تسوق بعملتك',
    subheadlineEn: 'SYP, USD, EUR - We support multiple currencies',
    subheadlineAr: 'ليرة سورية، دولار، يورو - ندعم عملات متعددة',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/multi-currency-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/multi-currency-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/multi-currency-mobile-768x400.jpg',
    imageAltEn: 'Multi-Currency Support',
    imageAltAr: 'دعم العملات المتعددة',
    ctaTextEn: 'Change Currency',
    ctaTextAr: 'غيّر العملة',
    ctaVariant: 'secondary',
    ctaSize: 'large',
    ctaColor: 'forest-green',
    ctaIcon: 'currency_exchange',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'page',
    targetUrl: '/currency-settings',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'multi-currency-2025',
    textColor: 'light',
    overlayColor: '#1b5e20',
    overlayOpacity: 0.5,
    contentAlignment: 'left',
    contentVerticalAlignment: 'center',
    type: 'brand_story',
    priority: 6,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-12-31T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: null,
    syrianSpecialties: null,
    culturalContextEn: 'Shop conveniently in your preferred currency. We support Syrian Pound (SYP), US Dollar (USD), and Euro (EUR) with real-time exchange rates.',
    culturalContextAr: 'تسوق بسهولة بالعملة التي تفضلها. ندعم الليرة السورية والدولار الأمريكي واليورو بأسعار صرف حية.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: null,
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },

  // ============================================
  // FLASH SALES & PROMOTIONS (Banners 21-22)
  // ============================================

  {
    // Banner 21: Flash Sale - Damascus Steel
    nameEn: 'Flash Sale - Damascus Steel 40% Off',
    nameAr: 'تخفيض سريع - الفولاذ الدمشقي خصم 40%',
    headlineEn: 'Flash Sale: 40% Off Damascus Steel',
    headlineAr: 'تخفيض سريع: خصم 40% على الفولاذ الدمشقي',
    subheadlineEn: 'Limited time offer - Only 48 hours left!',
    subheadlineAr: 'عرض لفترة محدودة - 48 ساعة فقط!',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/flash-sale-steel-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/flash-sale-steel-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/flash-sale-steel-mobile-768x400.jpg',
    imageAltEn: 'Flash Sale Damascus Steel',
    imageAltAr: 'تخفيض سريع الفولاذ الدمشقي',
    ctaTextEn: 'Shop Now',
    ctaTextAr: 'تسوق الآن',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'syrian-red',
    ctaIcon: 'local_fire_department',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'campaign',
    targetUrl: '/flash-sale/damascus-steel',
    trackingSource: 'hero-slider',
    trackingMedium: 'flash-sale',
    trackingCampaign: 'flash-sale-steel-jan2025',
    textColor: 'light',
    overlayColor: '#b71c1c',
    overlayOpacity: 0.6,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'flash_sale',
    priority: 10,
    scheduleStart: new Date('2025-01-15T00:00:00Z'),
    scheduleEnd: new Date('2025-01-17T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Damascus',
    syrianSpecialties: ['Damascus Steel'],
    culturalContextEn: 'Rare opportunity to own authentic Damascus steel at 40% off. Limited stock available - first come, first served!',
    culturalContextAr: 'فرصة نادرة للحصول على الفولاذ الدمشقي الأصيل بخصم 40%. المخزون محدود - الأولوية للأوائل!',
    unescoRecognition: true,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Damascus',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: false, // Activate during flash sale period
  },

  {
    // Banner 22: New Vendor - Aleppo Artisans
    nameEn: 'New Vendor - Aleppo Master Artisans',
    nameAr: 'بائع جديد - أساتذة حرفيين حلب',
    headlineEn: 'Welcome New Artisan Collective',
    headlineAr: 'مرحباً بتجمع الحرفيين الجديد',
    subheadlineEn: '50+ master artisans from Aleppo join SouqSyria',
    subheadlineAr: 'أكثر من 50 حرفياً أستاذاً من حلب ينضمون إلى سوق سوريا',
    imageUrlDesktop: 'https://cdn.souqsyria.com/hero/new-vendor-aleppo-desktop-1920x800.jpg',
    imageUrlTablet: 'https://cdn.souqsyria.com/hero/new-vendor-aleppo-tablet-1024x600.jpg',
    imageUrlMobile: 'https://cdn.souqsyria.com/hero/new-vendor-aleppo-mobile-768x400.jpg',
    imageAltEn: 'New Aleppo Artisans',
    imageAltAr: 'حرفيون حلب الجدد',
    ctaTextEn: 'Meet the Artisans',
    ctaTextAr: 'تعرف على الحرفيين',
    ctaVariant: 'primary',
    ctaSize: 'large',
    ctaColor: 'golden-wheat',
    ctaIcon: 'group',
    ctaIconPosition: 'right',
    ctaVisible: true,
    targetType: 'page',
    targetUrl: '/vendors/aleppo-artisan-collective',
    trackingSource: 'hero-slider',
    trackingMedium: 'campaign',
    trackingCampaign: 'new-vendor-aleppo-2025',
    textColor: 'light',
    overlayColor: '#4a148c',
    overlayOpacity: 0.5,
    contentAlignment: 'center',
    contentVerticalAlignment: 'center',
    type: 'brand_story',
    priority: 7,
    scheduleStart: new Date('2025-01-01T00:00:00Z'),
    scheduleEnd: new Date('2025-02-28T23:59:59Z'),
    timezone: 'Asia/Damascus',
    syrianRegion: 'Aleppo',
    syrianSpecialties: ['Traditional Crafts', 'Aleppo Soap', 'Textiles', 'Woodwork'],
    culturalContextEn: 'We\'re proud to welcome a collective of 50+ master artisans from Aleppo, preserving traditional crafts and bringing authentic Syrian heritage to your home.',
    culturalContextAr: 'نحن فخورون بالترحيب بتجمع من أكثر من 50 حرفياً أستاذاً من حلب، يحافظون على الحرف التقليدية ويحضرون التراث السوري الأصيل إلى منزلك.',
    unescoRecognition: false,
    artisanNameEn: null,
    artisanNameAr: null,
    artisanBioEn: null,
    artisanBioAr: null,
    artisanLocation: 'Aleppo',
    artisanExperience: null,
    approvalStatus: 'approved',
    isActive: true,
  },
];

/**
 * Export for seeding service
 */
export default heroBannersSeedData;
